ARG ALPINE_VERSION=3.20
ARG GO_ALPINE_VERSION=3.20
ARG GO_VERSION=1.23
ARG XCPUTRANSLATE_VERSION=v0.6.0
ARG GOLANGCI_LINT_VERSION=v1.61.0
ARG MOCKGEN_VERSION=v1.6.0
ARG BUILDPLATFORM=linux/amd64

FROM golang:1.23-alpine3.20 AS build
RUN apk --update add g++ findutils
WORKDIR /tmp/gobuild
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN go build -trimpath -o gluetun-exporter main.go

FROM golang:1.23-alpine3.20

COPY --from=build /tmp/gobuild/gluetun-exporter /opt/gluetun-exporter

EXPOSE 8001/tcp

# Set the default ENVIRONMENT variables
ENV GLUETUN_HOST=gluetun\
    GLUETUN_PASSWORD=\
    GLUETUN_USERNAME=\
    GLUETUN_APIKEY=\
    GLUETUN_PORT=8000\
    EXPORTER_PORT=8001\
    EXPORTER_INTERVAL=30\
    EXPORTER_BUNDLED=false\
    EXPORTER_DEBUG=false

ENTRYPOINT ["/opt/gluetun-exporter"]
