{
 "title": "Gluetun-Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gluetun_vpn_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VPN Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gluetun_vpn_status{instance=~\"$instance\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Forwarded Ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gluetun_forwarded_ports_total{instance=~\"$instance\"}",
     "legendFormat": "Auto"
    }
   ]
  },
  {
   "title": "IP",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gluetun_vpn_infos{instance=~\"$instance\"}",
     "legendFormat": "Auto"
    }
   ]
  },
  {
   "title": "City",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gluetun_vpn_infos{instance=~\"$instance\"}",
     "legendFormat": "Auto"
    }
   ]
  },
  {
   "title": "Country",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gluetun_vpn_infos{instance=~\"$instance\"}",
     "legendFormat": "Auto"
    }
   ]
  },
  { "title": "Network Stats (Bundled only)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gluetun_rx_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expression": "-1 * $B", "type": "math" }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gluetun_rx_packets{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expression": "-1 * $B", "type": "math" }
   ]
  },
  {
   "title": "Collisions",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gluetun_collisions{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gluetun_rx_errors{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expression": "-1 * $B", "type": "math" }
   ]
  },
  {
   "title": "Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gluetun_rx_dropped{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    { "expression": "-1 * $B", "type": "math" }
   ]
  }
 ]
}