{
 "title": "Service / Gluetun",
 "tags": [
  "docker",
  "service"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gluetun_vpn_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VPN Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gluetun_vpn_status{instance=~\"$instance\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Forwarded Ports",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gluetun_forwarded_ports_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infos",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "gluetun_vpn_infos{instance=~\"$instance\"}",
     "legendFormat": "Auto"
    }
   ]
  }
 ]
}